---
name: build-publish

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.8
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Check style with flake8
        run: poetry run flake8 ways_py/ tests/
      - name: Check type hinting with mypy
        run: poetry run mypy --strict --config-file=mypy.ini ways_py/ tests/
      - name: Test notebooks
        run: poetry run pytest --nbmake "./notebooks"
      - name: Unit & coverage test with pytest
        run: poetry run pytest --headless=True -rP

  docs:
    if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/develop'
    runs-on: macos-10.15
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.8
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force

  publish:
    runs-on: macos-10.15
    needs: [build, docs]
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.8
      - name: Install poetry
        run: pip install poetry
      - name: Bump version number
        run: poetry version patch
      - name: Build package
        run: poetry build
      - name: Publish package
        run: poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
