name: docs

on:
  # These events I think only fire for the default branch (develop). So docs currently build only on
  # develop, which is reasonable for now. (The reason for using the workflow_run event, rather than
  # simply having docs be one of the jobs in build-publish, is that it gives us a separate status badge
  # for the docs job.)
  workflow_run:
    workflows: ["build-publish"]
    types:
      - completed

jobs:
  docs:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.9
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - run: poetry run pdocs as_html ways_py -o docs
      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs/ways_py
