name: publish

on:
  workflow_run:
    workflows: ['build']
    branches: [release]
    types:
      - completed

jobs:
  publish:
    runs-on: macos-10.15
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.9
      - name: Install poetry
        run: pip install poetry
      - name: Bump version number
        run: poetry version patch
      - name: Build package
        run: poetry build
      - name: Publish package
        run: poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
